### ISSUE TITLE
Unexpected exception when instantiating class.

### ISSUE THREAD

**Issue by zo3n** [multitheftauto/mtasa-php-sdk#15]
```php
<?php

require_once 'vendor/autoload.php';

use MultiTheftAuto\Sdk\Mta;
use MultiTheftAuto\Sdk\Model\Server;
use MultiTheftAuto\Sdk\Model\Authentication;

try {

    $server = new Server('127.0.0.1', 22005);
    $auth = new Authentication('myUser', 'myPassword');
    $mta = new Mta($server, $auth); # this line gives the error

}catch(Exception $e){
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}

?>
```

This is a sample concept code extracted from my PHP script. I have logically replaced ip, port, user, password with my own credentials in my script, but no matter what's written there, $mta line gives the error which is in the title of this issue.

**Comment by ecastro98** [comment]
Hi! Sorry for the delay. Github doesn't notify me when an issue is created.
Try to execute `composer require http-interop/http-factory-guzzle`.
Seems like the HTTPlug documentation (TL;DR) is missing to require one more pacakge. I've just updated the [README to fix this](https://github.com/multitheftauto/mtasa-php-sdk/blob/master/README.md#httplug-client-abstraction)

**Comment by zo3n** [comment]
Thanks! That solved it.
