### ISSUE TITLE
Tags need to use the `v` prefix

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-php-sdk#4]
v1.0.0 and v1.0.1 instead of 1.0.0 and 1.0.1 as per github's recommendations:

![image](https://user-images.githubusercontent.com/923242/66176768-e1b7b600-e656-11e9-8ff4-4850715a0c13.png)

It would be nice if you could update the existing tags too please!

**Comment by ecastro98** [comment]
Done

**Comment by qaisjp** [comment]
Thank you !!!
