### ISSUE TITLE
Function call only allows arrays as parameters

### ISSUE THREAD

**Issue by MegaThorx** [multitheftauto/mtasa-php-sdk#5]
[https://github.com/multitheftauto/mtasa-php-sdk/blob/master/src/Model/Resource.php#L60](https://github.com/multitheftauto/mtasa-php-sdk/blob/c13ab41b41ad61afb29db5a32f2d66befbc0fc86/src/Model/Resource.php#L60)

The `array` prevents that you just pass numbers or strings as a parameter.

`$this->mta->getResource('vrp')->call('phpSDKKickPlayer', $adminId, $targetId, $reason)`

For now I need to wrap all the parameters into an array and unpack it in the script.

`$this->mta->getResource('vrp')->call('phpSDKKickPlayer', ['adminId' => $adminId, 'targetId' => $targetId, 'reason' => $reason])`

**Comment by qaisjp** [comment]
Are you sure? https://wiki.php.net/rfc/argument_unpacking#proposal

**Comment by MegaThorx** [comment]
![image](https://user-images.githubusercontent.com/923242/66268838-54808700-e839-11e9-8e09-679ecddd189a.png)

`array ...$arguments` forces that every parameter must be from type array. If I change the line to `...$arguments` then it works.

**Comment by ecastro98** [comment]
The PR was merged. Thanks!
